import "./globals.css";
import type { Metadata } from "next";
import { Mitr } from "next/font/google";
import NavBar from "./components/NavBar";

const mitr = Mitr({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={mitr.className}>
        <main className="relative flex flex-col items-center justify-start w-[97vw]">
          {children}
          <NavBar />
        </main>
      </body>
    </html>
  );
}
