import "./globals.css";
import type { Metadata } from "next";
import { Comfortaa } from "next/font/google";
import NavBar from "./components/NavBar";

const comfortaa = Comfortaa({
  subsets: ["latin"],
  display: "swap",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={comfortaa.className}>
        <main className="relative flex flex-col overflow-hidden">
          {children}
          <NavBar />
        </main>
      </body>
    </html>
  );
}
